export const UI_TEXT = {
  training: {
    activeResumePrompt: "You have an active training. Resume it instead?",
    startLabels: {
      start: "Start",
      pause: "Pause",
      continue: "Continue",
    },
    nextLabels: {
      next: "Next",
      finish: "Finish",
      none: "None",
    },
    headers: {
      workoutFallback: "Workout",
    },
    cards: {
      now: "Now",
      next: "Next",
    },
    states: {
      noTraining: "No training",
      noExercises: "No exercises yet.",
      startToSeeSets: "Start training to see sets.",
    },
  },
  workouts: {
    defaultName: "Push Day",
    repeatOptions: {
      show: "Repeat options",
      hide: "Hide repeat options",
      none: "No repeats",
    },
    editMode: {
      edit: "Edit workout",
      create: "New workout",
      updateButton: "Update Workout",
      saveButton: "Save Workout",
      updatedToast: "Workout updated",
      createdToast: "Workout created",
    },
    form: {
      durationHint: "Duration (Go style, e.g. 45s, 1m30s)",
      nameOptional: "Name (optional)",
      nameRequired: "Name",
      pausePlaceholder: "Pause",
    },
  },
  prompts: {
    selectUserFirst: "Select a user first.",
    templateName: "Template name",
    workoutNameOptional: "Workout name (optional)",
    exerciseName: "Exercise name",
    coreExerciseName: "Core exercise name",
    deleteExerciseConfirm: "Delete this exercise?",
    unsavedChanges: "You have unsaved changes. Close without saving?",
    selectWorkoutFirst: "Select a workout first.",
    selectWorkoutToStart: "Select a workout to start.",
    selectWorkoutToExport: "Select a workout to export.",
    workoutNotFound: "Workout not found.",
  },
  errors: {
    loginRequiredSave: "You must be logged in to save workouts.",
    loginRequiredUpdate: "You must be logged in to update workouts.",
    addStepRequired: "Add at least one step.",
    exerciseNameRequired: "Exercise name required",
  },
  toasts: {
    shared: "Shared.",
    templateCopied: "Template copied to clipboard.",
    workoutDeleted: "Workout deleted.",
    copiedSummary: "Copied summary",
    workoutExported: "Workout exported.",
    workoutImported: "Workout imported.",
    createdPersonalCopy: "Created a personal copy.",
    invalidWorkoutJson: "Invalid workout JSON.",
    passwordUpdated: "Password updated.",
    backfillComplete: "Exercise catalog backfill complete.",
  },
  labels: {
    workout: "Workout",
    pause: "Pause",
    step: "Step",
    superset: "Superset",
    subsetSound: "Subset sound",
    sound: "Sound",
    duration: "Duration",
    reps: "Reps",
    autoAdvance: "Auto-advance",
  },
  titles: {
    close: "Close",
    repStep: "Rep-based step with optional target time.",
    timedBreak: "Timed break (auto-advance ends it).",
    moveUp: "Move up",
    moveDown: "Move down",
    removeStep: "Remove step",
    removeSubset: "Remove subset",
    removeExercise: "Remove exercise",
    supersetTooltip: "Superset: Next moves to the next subset.",
    autoAdvancePause: "Auto-advance ends the pause automatically.",
    defaultPauseAutoAdvance: "Auto-advance pauses by default",
    repeatRestAfterLast: "Repeat the rest step after the final round",
    pauseOnTabHidden: "Pause training when tab is hidden",
    showHours: "Show hours in timers",
  },
  actions: {
    start: "Start",
    pause: "Pause",
    continue: "Continue",
    select: "Select",
    new: "New",
  },
  options: {
    none: "None",
    mmss: "MM:SS",
    hhmmss: "HH:MM:SS",
  },
  placeholders: {
    workoutName: "Push Day",
    selectTheme: "Select theme",
    selectSound: "Select sound",
    selectWorkout: "Select workout",
    selectExercise: "Select exercise",
    reps: "12",
    duration: "e.g. 45s",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    yourName: "Your name",
  },
  themes: {
    auto: "Auto (system)",
    dark: "Dark",
    light: "Light",
  },
  roles: {
    admin: "Admin",
    user: "User",
  },
  admin: {
    revokeAdmin: "Revoke Admin",
    makeAdmin: "Make Admin",
    backfill: {
      working: "Backfilling…",
      action: "Backfill exercises",
    },
  },
  exercises: {
    core: "Core",
    personal: "Personal",
    unlinked: "Unlinked",
    rename: "Rename exercise",
    createCopy: "Create personal copy from core",
  },
  account: {
    saving: "Saving…",
    save: "Save",
    registrationDisabledTitle: "Registration disabled",
    registrationDisabledHint: "Ask an admin to create an account for you.",
  },
  pages: {
    auth: {
      loginTitle: "Log in",
      createUserTitle: "Create user",
      registrationDisabledTitle: "Registration disabled",
      registrationDisabledHint: "Ask an admin to create an account for you.",
    },
    admin: {
      title: "Admin",
      hint: "Manage users and maintenance tasks.",
      usersTitle: "Users",
      usersHint: "Manage roles and switch user.",
      createUserTitle: "Create user",
      maintenanceLabel: "Maintenance",
      backfillHint:
        "Backfill promotes workouts exercises into the Core catalog.",
    },
    exercises: {
      title: "Exercises",
      hint: "Manage reusable exercises.",
      addExercise: "Add Exercise",
      addCoreExercise: "Add Core Exercise",
      empty: "No exercises yet.",
    },
    templates: {
      title: "Templates",
      hint: "Create workouts from shared templates.",
      refresh: "Refresh",
      loading: "Loading templates…",
      apply: "Use for user",
      empty: "No templates yet.",
    },
    history: {
      title: "Training history",
      hint: "Completed trainings for the selected user.",
    },
    training: {
      title: "Training",
      overrunTitle: "Still training?",
      overrunMessage: "You passed the target. Auto-pause in",
      overrunPostpone: "Postpone (+30s)",
    },
    profile: {
      title: "Profile",
      hint: "Manage your local account preferences.",
      accountLabel: "Account",
      appearanceLabel: "Appearance",
      defaultsLabel: "Defaults",
      timeFormatLabel: "Time format",
      transferLabel: "Workout transfer",
      exportLabel: "Export workout",
      exportButton: "Export",
      importButton: "Import",
      settingsTab: "Settings",
      passwordTab: "Password",
      transferTab: "Export/Import",
      displayNameLabel: "Display name",
      currentPasswordLabel: "Current password",
      newPasswordLabel: "New password",
      confirmPasswordLabel: "Confirm password",
      mismatch: "Passwords do not match.",
      updatePasswordButton: "Update password",
      themeLabel: "Theme",
      defaultStepSoundLabel: "Default step sound",
      defaultPauseDurationLabel: "Default pause duration",
      defaultPauseSoundLabel: "Default pause sound",
      defaultPauseAutoAdvanceLabel: "Default pause auto-advance",
      repeatRestAfterLastLabel: "Repeat rest after last (default)",
      pauseOnTabHiddenLabel: "Pause training when tab is hidden",
      showHoursLabel: "Show hours in timers",
      autoTheme: "Auto (system)",
      darkTheme: "Dark",
      lightTheme: "Light",
    },
  },
  dialog: {
    confirmTitle: "Confirm",
    messageTitle: "Message",
    confirmButton: "Confirm",
    promptButton: "Save",
    okButton: "OK",
    cancelButton: "Cancel",
  },
  nav: {
    login: "Login",
    train: "Training",
    workouts: "Workouts",
    templates: "Templates",
    exercises: "Exercises",
    history: "History",
    profile: "Profile",
    admin: "Admin",
  },
  history: {
    notStarted: "Not started",
    notFinished: "Not finished",
    noHistory: "No history yet.",
    activeTraining: "Active training",
    inProgress: "in progress",
    resume: "Resume",
    finishedPrefix: "Finished",
    aiSummary: "AI-ready summary",
    loadingSteps: "Loading steps…",
    copySummary: "Copy summary",
  },
  auth: {
    enterPassword: "Enter a password",
    yourPassword: "Your password",
  },
  accessibility: {
    navToggle: "Toggle navigation",
    brandAlt: "Motus",
  },
};
