services:
  motus-db:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_DB: motus
      POSTGRES_USER: motus
      POSTGRES_PASSWORD: motus
    ports:
      - "127.0.0.1:${MOTUS_POSTGRES_PORT:-5431}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U motus -d motus"]
      interval: 2s
      timeout: 3s
      retries: 30
    volumes:
      - motus-db-data:/var/lib/postgresql/
  # motus-pgadmin:
  #   image: dpage/pgadmin4:9
  #   container_name: motus-pgadmin
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@motus.app
  #     PGADMIN_DEFAULT_PASSWORD: motus
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - motus-db

volumes:
  motus-db-data:
